backend:
  name: git-gateway
  branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://codestitch.app/frontend/images/logo.png

media_folder: "public/assets/images/blog"
public_folder: "/assets/images/blog"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Vārds", name: "title", widget: "string" }
      - {
          label: "Dzimums",
          name: "gender",
          widget: "select",
          options: ["Ķēve", "Kastrāts", "Ērzelis"],
          default: ["Ķēve"],
        }
      - {
          label: "Pārdots",
          name: "sold",
          widget: "select",
          options: ["Pārdots", "Pieejams"],
          default: ["Pieejams"],
        }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Dzimšanas gads", name: "year", widget: "string" }
      - { label: "Īsais apraksts", name: "description", widget: "string" }
      - { label: "Sludināuma datums", name: "date", widget: "datetime" }
      - { label: "Galvenā bilde", name: "image", widget: "image" }
      - { label: "Bildes nosaukums", name: "imageAlt", widget: "string" }
      - { label: "Pilnais apraksts", name: "body", widget: "markdown" }
